apiVersion: v1
kind: Namespace
metadata:
  name: status-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-service
  namespace: status-service
  labels:
    app: status-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-service
  template:
    metadata:
      labels:
        app: status-service
    spec:
      containers:
        - name: status-service
          image: eu.gcr.io/adam-playground-315708/status-service:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: status-service
  namespace: status-service
  labels:
    app: status-service
spec:
  selector:
    app: status-service
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
