---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: banking-demo-gw
  labels:
    app.kubernetes.io/component: istio
    app.kubernetes.io/name: banking-demo
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.styra-sa.com"
  # - port:
  #     number: 443
  #     name: https
  #     protocol: HTTPS
  #   tls:
  #     mode: SIMPLE
  #     credentialName: styra-sa.com.certs
  #   hosts:
  #   - "*.styra-sa.com"
