apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal
  template:
    metadata:
      labels:
        app: portal
    spec:
      containers:
        - name: portal
          image: europe-west4-docker.pkg.dev/adam-playground-315708/microservice-demo/portal:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app: portal
spec:
  selector:
    app: portal
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
