name: Deploy services to Kubernetes

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: get-credentials
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: cluster-1
        location: europe-north1-a
        credentials: ${{ secrets.GKE_SERVICE_ACCOUNT }}
    - name: Deploy to Kubernetes
      run: deploy-everything.sh


