name: Deploy services to Kubernetes

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: login-to-artifact-registry
      env:
        GCP_SA_CREDS: ${{ secrets.GKE_SERVICE_ACCOUNT }}
      run: |
        echo "${GCP_SA_CREDS}" | base64 > key.json
        cat key.json | docker login -u _json_key_base64 --password-stdin https://europe-west4-docker.pkg.dev
    - name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: adopt-hotspot
        cache: maven
    - id: build-push-images
      run: |
        cd entitlements
        ./build.sh
        cd account
        ./build.sh
        cd ../frontend-portal
        ./build.sh
        cd ../status-service
        ./build.sh
    - id: get-credentials
      uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: cluster-1
        location: europe-north1-a
        credentials: ${{ secrets.GKE_SERVICE_ACCOUNT }}
    - name: Deploy to Kubernetes
      run: ./deploy-everything.sh


