name: Deploy services to Kubernetes

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: adopt-hotspot
          cache: maven
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: adamsandor83
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: build-push-images
        run: |
          cd entitlements
          ./push.sh
          cd ../account
          ./push.sh
          cd ../frontend-portal
          ./push.sh
      - id: gke-auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SERVICE_ACCOUNT }}
      - id: gke-get-credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: expo-banteng
          location: us-west2-a
      - name: Deploy to Kubernetes
        run: |
          sed -i 's/banking.styra-demo.com/banking-demo.expo.styralab.com/' provisioning/k8s/account-deploy.yaml
          sed -i 's/banking.styra-demo.com/banking-demo.expo.styralab.com/' provisioning/k8s/entitlements-deploy.yaml
          sed -i 's/banking.styra-demo.com/banking-demo.expo.styralab.com/' provisioning/k8s/portal-deploy.yaml
          NS=banking-demo
          kubectl apply -f provisioning/k8s/account-deploy.yaml -n $NS
          kubectl apply -f provisioning/k8s/entitlements-deploy.yaml -n $NS
          kubectl apply -f provisioning/k8s/portal-deploy.yaml -n $NS
          kubectl delete pod -l app.kubernetes.io/name=banking-demo -n $NS


