name: Verify Pull Request

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Styra CLI
        env:
          STYRA_API_TOKEN: ${{ secrets.ADAMSANDOR_DAS_API_TOKEN }}
          STYRA_CLI_URL: https://adamsandor.svc.styra.com/v1/docs/bin/linux/amd64/styra
        run: |
          curl -s -w "%{http_code}" -H "Authorization: Bearer ${STYRA_API_TOKEN}" -o styra ${STYRA_CLI_URL}
          mv styra /usr/local/bin/styra
          chmod +x /usr/local/bin/styra
          styra configure -i https://adamsandor.svc.styra.com -t ${STYRA_API_TOKEN}
      - name: Replay decision logs
        working-directory: policy
        run: |
          styra validate logreplay -p global/jwt=library/global/jwt/jwt.rego --system=dc105efba51d4f59b419d3979d8ae0e6 -o json > replay-result1.json
          styra validate logreplay -p entitlements=system/api/entitlements/entitlements.rego --system=fca9a74811204ea6b1d812f115cede2f -o json > replay-result2.json
          echo ::set-output name=replay-result::$(cat replay-result1.json)
      - name: Add results to PR
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ABC: "abcdef"
        with:
          message: |
            "${{ steps.vars.outputs.replay-result }}"