name: Verify Policy Change Pull Request

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Styra CLI
        env:
          STYRA_API_TOKEN: ${{ secrets.STYRA_API_TOKEN }}
        run: |
          curl -s -o styra https://docs.styra.com/bin/linux/amd64/styra
          mv styra /usr/local/bin/styra
          chmod +x /usr/local/bin/styra
          styra configure -i https://expo.styra.com -t ${STYRA_API_TOKEN}
      - name: Replay decision logs
        id: replay
        run: |
          mkdir ./replay-results
          echo "Replaying decision logs for changes in Entitlements System"
          styra validate logreplay -p entitlements=policy/system/portal/entitlements/entitlements.rego --system=ded698029538485d9745a62d22a0c3ac -o json > ../replay-results/replay-result.json
          echo "------"
          ls -l ./replay-results
      - uses: actions/github-script@v5
        name: Add results to PR
        with:
          script: |
            const fs = require('fs')

            var numberOfChanges = 0
            var numberOfErrors = 0
            var samplesLogged = 0
            var results = ""

            const files = fs.readdirSync("replay-results")
            files.forEach((file) => {
              const resultData = JSON.parse(fs.readFileSync("replay-results/" + file, 'utf8'))

              numberOfChanges += resultData.stats.results_changed;
              numberOfErrors += resultData.stats.entries_failed;
              resultData.samples.forEach((sample, i) => {
                if (samplesLogged < 4) {
                  samplesLogged += 1
                  results += "### Sample " + samplesLogged + ":\n"
                          + "Path: `" + sample.path + "`\n"
                          + "Input: \n```\n" + JSON.stringify(sample.input, null, 2) + "\n```\n"
                          + "Output before change:\n```\n" + JSON.stringify(sample.result, null, 2) + "\n```\n"
                          + "Output after change:\n```\n" + JSON.stringify(sample.new_result, null, 2) + "\n```\n\n"
                }
              })
            })

            var comment = "No changes in decision logs found by replay"
            if (numberOfChanges > 0) {
              comment = "Warning: The changes in this PR lead to " + numberOfChanges + " changes when replaying previous decision logs:\n"
              + results
            } else if (numberOfErrors > 0) {
              comment = "Warning: The changes in this PR lead to " + numberOfErrors + " errors when replaying previous decision logs!"
            }

            console.log(comment)
            github.rest.issues.createComment({
              issue_number: context.issue.number ? context.issue.number : 3,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })

